spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/pingerboard_db
    username: postgres

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
